[tox]
skip_missing_interpreters = True
envlist = style, pylint, py3
isolated_build = True

[testenv]
deps = respx
    pytest-cov
commands =
    pytest -v --cov=src tests \
        -o junit_family=xunit2 \
        --cov-report term \
        --cov-report html:tests/htmlcov \
        --cov-report xml:tests/coverage.xml

[testenv:pylint]
deps = pylint
commands =
    pylint -E src

[testenv:style]
deps = pycodestyle
commands =
    pycodestyle --show-source --show-pep8 \
        --ignore=E501,F401,E128,E402,E731,F821 src
